name: py5coding
channels:
  - conda-forge
dependencies:
  - python=3.8
  - cairo
  - cairosvg
  - jedi=0.17.2
  - jupyterlab
  - line_profiler
  - noise
  - openjdk=11.0.8
  - pip
  - pip:
      - py5
